### ISSUE TITLE
compliment, not an issue.

### ISSUE THREAD

**Issue by koaning** [arose13/Notebooks#1]
this one was fun to read. 

https://github.com/arose13/Notebooks/blob/master/Repeated%20Radial%20Basis%20Function.ipynb

**Comment by arose13** [comment]
Now you can see why I said I poop when I saw your PyData talk (unless you like for RBFs were a phase).

I even used them in your hated tensorflow 😛 https://github.com/arose13/Notebooks/blob/master/Radial%20Basis%20Function%20Neural%20Networks.ipynb

**Comment by koaning** [comment]
i think tensorflow is cool, it’s just that it’s cooler when you don’t need it.
